apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: node-express
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: node-express
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: node-express
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: harbor.mike.lab/my-project-ootb/ootb-supply-chain:latest@sha256:9e752996b30b0e595d310ea0b302c1d05b03b7c8c5f237f0eee97587f1669dfd
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: node-express
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: node-express
    spec:
      containers:
      - image: harbor.mike.lab/my-project-ootb/ootb-supply-chain/node-express-tap-dev@sha256:5308599d342f38b70a3900ab150ab93b342c9cadae492b6b5c131a8f9955d09c
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

